// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfujegzzzfpenknponqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmdWplZ3p6emZwZW5rbnBvbnFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODI2MjcsImV4cCI6MjA2MTA1ODYyN30.z80NbCmAMp_XaZJep3L--GpGb9AoalsRU9RdvqqUYjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);